services:
  - type: web
    name: hospital-bam-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-bam-db
          property: connectionString

databases:
  - name: hospital-bam-db
    databaseName: hospitalmp
    user: postgres
